version: "3"

services:
  golang:
    image: golang
    build: ./src
    ports:
      - 1234:80
    volumes: 
      - ./src:/dockerapp
    depends_on:
      - "db"

  db:
    image: db
    build: ./db
    container_name: 'db'
    ports:
      - 7654:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrate/00001_setup.sql:/docker-entrypoint-initdb.d/00001_setup.up.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  pgdata: