version: "3"

services:
  golang:
    image: golang
    build: ./src
    ports:
      - 1234:8080
    depends_on:
      - "db"

  db:
    image: db
    build: ./db
    container_name: 'db'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
volumes:
  pgdata: