name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - name: Install dependencies
        working-directory: ./main-api
        run: go get .
      - name: Build
        working-directory: ./main-api
        run: go build -v ./...
      - name: Test with the Go CLI
        working-directory: ./main-api
        run: go test ./...